# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - develop

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    displayName: "npm install and build"

  - script: |
      npx ng test --watch=false --codeCoverage=true
    displayName: "Run integration tests"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TESTS-*.xml'
    displayName: 'Publish Test Results' 

  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage/ng-azure-devops/cobertura-coverage.xml'
    displayName: 'Publish Code Coverage Results'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/ng-azure-devops'
      ArtifactName: 'web-app'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'