# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - develop

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g @angular/cli
    displayName: "Install Angular"

  - script: npm install
    displayName: "Install Dependencies"

  - script: npx ng build --prod
    displayName: "Build"

  - script: |
      npx ng test --watch=false --codeCoverage=true
    displayName: "Run integration tests"

  - script: npx ng lint
    displayName: 'Code Analysis'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/TESTS-*.xml"
    displayName: "Publish Test Results"

  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(Build.SourcesDirectory)/coverage/ng-azure-devops/cobertura-coverage.xml"
    displayName: "Publish Code Coverage Results"

  - task: CopyPublishBuildArtifacts@1  
    displayName: 'Copy Publish Artifact: test'  
    inputs:  
      CopyRoot: dist  
      Contents: '**'  
      ArtifactName: test  
      ArtifactType: Container  

  - task: DownloadPipelineArtifact@2  
    displayName: 'Download Pipeline Artifact'  
    inputs:  
      targetPath: ' $(Build.ArtifactStagingDirectory)/dist/AngularTest'
